### PR TITLE
Ghostnet support for tests and live code examples

### LINKED ISSUE #2243: Chore - convert Docs live code examples to use ghostnet
**Description**
Convert Docs live code examples to use ghostnet

**Steps To Reproduce**
Follow the instructions at https://ecadlabs.testpad.com/script/333#//

**Expected behaviour**
The live code samples will work with ghostnet

These contracts have already been originated for ghostnet and are to be used in the Docs:
```bash
SaplingLiveCodeContract : KT1ToBD7bovonshNrxs3i4KMFuZ8PE2LUmQf
IncrementContract : KT1BJadpDyLCACMH7Tt9xtpx4dQZVKw9cDF7
Deploying Michelson Tutorial contract...
Michelson Tutorial Contract address KT1M5C76aSjpWXdoBvuzRdi3UJoC3jEzrSUW
LambdaViewContract : KT1MhfAnNbg2oACFBP4VDU5bNY5MZUXdeDWs
LambdaViewWithTokenContract : KT1Ccr6ZMeB1mp9yJAqJTHK7F4xoFV9uc11T
MapWithSingleMapForStorage : KT1B3SpFJ1iHagwdkd1utVYP18RyYgZXeGio
MapWithPairasMapContract : KT1JDDU888CaVWFey2BYxpDzPBaYYn65Q4o3
MapWithComplexKeysContract : KT1GuenTpQEjxPzw81CHHvmSmSz9b5nmkpyz
MapWithInitialStorageContract : KT1PZb8sEVvsKQGzLwusyQRkJpSCDQ7WFfny
BigMapsMultipleValuesContract : KT1LPdW47Aba3kVpNMpRt7sx5yM1M4A8XmAW
BigMapsComplexStorageContract : KT1B2exfRrGMjfZqWK1bDemr3nBFhHsUWQuN
ContractCallFib : KT1KPDBat3prp2G81aDDLyJ38Vbq6YLYFQo8
ContractOnChainViews : KT1Anag1s3N7erRXrRAtPpRC2PRXrqcCJ43m
TokenContract : KT1LgpUbAhRjL18XPGTb4CYvJxpyQ8Ty8sj5
Tzip16StorageContract : KT1UoYTsDCFgBx88QYdCd3pgjwV6RiMVpZaY
Tzip16HTTPSContract : KT1MJ7wAZ9LBB797zhGJrXByaaUwvLGfe3qz
Tzip16SHA256Contract : KT1JbEzvHn2Y2DjVQ7kgK8H8pxrspG893JsX
Tzip16IPFSContract : KT1SDtsB4DHdh1QwFNgvsavxDwQJBdimgrcL
Tzip16OnChainContractJSON : KT1GZdLX8Zc6vmrifnUhppNVwt9s19yffLLW
Tzip16OnChainContractMultiply : KT1CVoo3PxuvH3BuBpNTYRDafAQ7aRTfj8bd
WalletContract : KT1TBxaaeikEUcVN2qdQY7n9Q21ykcX1NLzY
WalletAreYouThereContract : KT1SHiNUNmqBFGNysX9pmh1DC2tQ5pGmRagC
BigMapPackContract : KT1BqDUytxnBE37uPFQqQaLrVDfpShW8QRPX
```

### PR DESCRIPTION
**Pull request by michaelkernaghan**
Closes #2243

### CODE REVIEW

File: integration-tests/config.ts [hunk 1]
```diff
@@ -117,6 +118,26 @@ const limanetEphemeral = {
...
+  knownBaker: process.env['TEZOS_BAKER'] || 'tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD',
+  knownContract: process.env['TEZOS_GHOSTNET_CONTRACT_ADDRESS'] || knownContractPtGhostnet,
+  knownBigMapContract: process.env['TEZOS_GHOSTNET_BIGMAPCONTRACT_ADDRESS'] || knownBigMapContractPtGhostnet,
+  knownTzip1216Contract: process.env['TEZOS_GHOSTNET_TZIP1216CONTRACT_ADDRESS'] || knownTzip12BigMapOffChainContractPtGhostnet,
+  knownSaplingContract: process.env['TEZOS_GHOSTNET_SAPLINGCONTRACT_ADDRESS'] || knownSaplingContractPtGhostnet,
+  txRollupWithdrawContract: process.env['TEZOS_GHOSTNET_TX_ROLLUP_WITHDRAW_CONTRACT'] || '',
+  txRollupDepositContract: process.env['TEZOS_GHOSTNET_TX_ROLLUP_DEPOSIT_CONTRACT'] || '',
+  knownViewContract: process.env['TEZOS_GHOSTNET_ON_CHAIN_VIEW_CONTRACT'] || knownOnChainViewContractAddressPtGhostnet,
+  txRollupAddress: process.env['TEZOS_GHOSTANET_TXROLLUP_ADDRESS'] || txRollupAddressPtGhostnet,
+  protocol: Protocols.PtGhostnet,
```
Comment (danielelisi) [inline integration-tests/config.ts:134]: this should be `Protocols.PtLimaPtL` there is no Ghostnet protocol :grin:

Comment (michaelkernaghan) [reply integration-tests/config.ts:134]: yes, thanks. I was trying to make one.

Comment (michaelkernaghan) [reply integration-tests/config.ts:134]: This will still have to be migrated to each new protocol then. I was hoping to find a way to avoid that :)

Comment (danielelisi) [reply integration-tests/config.ts:134]: The protocol needs to be updated yes; however there will be no need to re-originate contracts

**Comment by danielelisi** [comment]
The PR title mentions switching the live code example to using Ghostnet but from looking at the diff I only see changes to the integration tests config

File: integration-tests/config.ts (hunk 1 above)
Comment (michaelkernaghan) [reply integration-tests/config.ts]: yup.  I can live with one line!

File: docs/complex_parameters.md [hunk 2]
```diff
@@ -200,6 +200,6 @@ importKey(Tezos, secretKey)
     println(`Waiting for ${op.hash} to be confirmed...`);
     return op.confirmation(1).then(() => op.hash);
 }).then(hash => {
-    println(`Operation injected: https://better-call.dev/kathmandunet/KT1Resnq6SvWRUXA9FaNczhJ278QzwPjWcGz/operations`);
+    println(`Operation injected: https://better-call.dev/ghostnet/KT1Resnq6SvWRUXA9FaNczhJ278QzwPjWcGz/operations`);
```
Comment (danielelisi) [inline docs/complex_parameters.md:203]: This operation doesn't exist on Ghostnet. Would it be better to remove these hardcoded links?

File: docs/complex_parameters.md [hunk 3]
```diff
@@ -169,7 +169,7 @@ importKey(Tezos, secretKey)
...
```
Comment (danielelisi) [inline docs/complex_parameters.md:172]: same as below

File: docs/estimate.md [hunk 4]
```diff
@@ -62,7 +62,7 @@ Tezos.estimate
 
 ```js live noInline wallet
 // import { TezosToolkit } from '@taquito/taquito';
-// const Tezos = new TezosToolkit('https://kathmandunet.api.tez.ie');
+// const Tezos = new TezosToolkit('https://ghostnet.api.tez.ie');
```
Comment (danielelisi) [inline docs/estimate.md:65]: Some URL mention the old `api.tez.ie` domain. Can you rename all of them to `ghostnet.ecadinfra.com` ?

File: docs/michelsonmap.md [hunk 5]
```diff
@@ -15,7 +15,7 @@ Taquito reads maps in the storage of smart contracts and translates them into an
 - _The key/value methods_: they allow you to manipulate the keys and values in the map
 - _The update methods_: they transform the map itself, for example, by deleting elements or clearing out the map entirely.
 
-This tutorial uses a [simple smart contract deployed on kathmandunet](https://better-call.dev/kathmandunet/KT1C6YRpA7puibK8by6RrV5uMg6LBBiHauTP/operations) with a map that contains addresses as keys and tez as values. We will use all the methods available in Taquito's `MichelsonMap` to check the map, extract values and modify them!
+This tutorial uses a [simple smart contract deployed on ghostnet](https://better-call.dev/ghostnet/KT1C6YRpA7puibK8by6RrV5uMg6LBBiHauTP/operations) with a map that contains addresses as keys and tez as values. We will use all the methods available in Taquito's `MichelsonMap` to check the map, extract values and modify them!
```
Comment (danielelisi) [inline docs/michelsonmap.md:18]: This contracts address needs to be updated to reflect the one one on Ghostnet

File: docs/quick_start.md [hunk 6]
```diff
@@ -190,4 +190,4 @@ Tezos.wallet
 
 [boilerplate]: https://github.com/ecadlabs/taquito-boilerplate
 [smart_contract_source]: https://ide.ligolang.org/p/2sVshnZ_Aat5pIuUypIBsQ
-[smart_contract_on_better_call_dev]: https://better-call.dev/kathmandunet/KT1GJ5dUyHiaj7Uuc8gqfsbdv5tTbEH3fiRP/operations
+[smart_contract_on_better_call_dev]: https://better-call.dev/ghostnet/KT1GJ5dUyHiaj7Uuc8gqfsbdv5tTbEH3fiRP/operations
```
Comment (danielelisi) [inline docs/quick_start.md:193]: Smart contract address needs to be updated

File: docs/rpc_nodes_integration_test.md [hunk 7]
```diff
@@ -9,7 +9,7 @@ author: Roxane Letourneau
 Remove `./rpc-nodes.spec.ts` from `"testPathIgnorePatterns"` in the package.json.
 2. In the integration test folder, run one of the following commands: 
     - **Hanghzounet**: `npm run test:hangzhounet rpc-nodes.spec.ts`
-    - **Kathmandunet**: `npm run test:kathmandunet rpc-nodes.spec.ts`
+    - **ghostnet**: `npm run test:ghostnet rpc-nodes.spec.ts`
     - **Both protocols**: `npm run test rpc-nodes.spec.ts`
```
Comment (danielelisi) [inline docs/rpc_nodes_integration_test.md:13]: These docs are actually out of date, let's remove them or update them with correct values

File: docs/wallet_API.md [hunk 8]
```diff
@@ -80,19 +80,19 @@ const wallet = new BeaconWallet(options);
...
-> Note: if you want to use the Kukai wallet for testing on kathmandunet, you must use the optional property `preferredNetwork` and set it to `kathmandunet`, otherwise the mainnet version of the Kukai wallet will open.
+> Note: if you want to use the Kukai wallet for testing on ghostnet, you must use the optional property `preferredNetwork` and set it to `ghostnet`, otherwise the mainnet version of the Kukai wallet will open.
 
 The Beacon wallet requires an extra step to set up the network to connect to and the permissions:
 
 ```js
 await wallet.requestPermissions({
   network: {
-    type: 'mainnet' | 'kathmandunet' | 'jakartanet' | 'custom',
+    type: 'mainnet' | 'ghostnet' | 'jakartanet' | 'custom',
```
Comment (danielelisi) [inline docs/wallet_API.md:90]: Also remove `jakartanet` and instead mention `limanet` ?

File: packages/taquito/src/constants.ts [hunk 9]
```diff
@@ -34,6 +34,7 @@ export enum Protocols {
   PtJakart2 = 'PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY',
   PtKathman = 'PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg',
   PtLimaPtL = 'PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW',
+  PtGhostnet = 'PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW',
```
Comment (danielelisi) [inline packages/taquito/src/constants.ts:37]: Let's not do this since Ghostnet isn't a protocol but just a network. Change the `protocol` parameter for Ghostnet in `config.ts` to be `PtLimaPtL` instead.

**Review by danielelisi — CHANGES_REQUESTED** [review]

File: docs/complex_parameters.md (hunk 2 above)
Comment (michaelkernaghan) [reply docs/complex_parameters.md:203]: We need the link to show the user it works. The operation doesn't;t exist yet, as I haven't finished the updates. PR is still a draft, I will get to this one.

File: docs/complex_parameters.md (hunk 3 above)
Comment (michaelkernaghan) [reply docs/complex_parameters.md:172]: same answer :)

File: docs/estimate.md (hunk 4 above)
Comment (michaelkernaghan) [reply docs/estimate.md:65]: Yes, thanks. Good one!  But it looks like that is the only example. Fixed.

File: docs/michelsonmap.md (hunk 5 above)
Comment (michaelkernaghan) [reply docs/michelsonmap.md:18]: Yes, it is the primary job to get all the contracts replaced with the correct new ones.

File: docs/quick_start.md (hunk 6 above)
Comment (michaelkernaghan) [reply docs/quick_start.md:193]: yes

File: docs/rpc_nodes_integration_test.md (hunk 7 above)
Comment (michaelkernaghan) [reply docs/rpc_nodes_integration_test.md:13]: Do you mean the whole page? or just these instructions? the instructions get updated. ARe they entirely wrong?

File: docs/wallet_API.md (hunk 8 above)
Comment (michaelkernaghan) [reply docs/wallet_API.md:90]: Yes, that will be done. kathmandunet -> limanet, jakartanet -> ghostnet

File: packages/taquito/src/constants.ts (hunk 9 above)
Comment (michaelkernaghan) [reply packages/taquito/src/constants.ts]: Done and it fixes it thanks

**Comment by michaelkernaghan** [comment]
There are problems with big maps examples and one of the contract view examples.   See this report
[TESTPAD REPORT taquito live code examples in docs to ghostnet _ ecadlabs.pdf](https://github.com/ecadlabs/taquito/files/10288558/TESTPAD.REPORT.taquito.live.code.examples.in.docs.to.ghostnet._.ecadlabs.pdf)

File: docs/estimate.md (hunk 4 above)
Comment (zainen) [reply docs/estimate.md:65]: is this supposed to stay as api.tez.ie?

File: docs/estimate.md [hunk 10]
```diff
@@ -130,10 +130,10 @@ Tezos.contract
...
```
Comment (zainen) [inline docs/estimate.md:133]: same

File: integration-tests/known-contracts-PtKathman.ts [hunk 11]
```diff
@@ -3,4 +3,4 @@ export const knownBigMapContractPtKathman = "KT1TZWawPbU6mCMa1x6hEZcuZ2RtJxqprsk
 export const knownTzip12BigMapOffChainContractPtKathman = "KT1WePZzvQxLFmb9QfpLK9rgUVcRPHzjQLhN";
 export const knownSaplingContractPtKathman = "KT1Riu8a1dbWRMmFpMzb9PgdJbhHAAHuvDyJ";
 export const knownOnChainViewContractAddressPtKathman = "KT1My3eKdYKW3H27jZ2oVcNCXGNBDBcTuYiR";
-export const txRollupAddressPtKathman = "txr1R5hkRCJjMugm2Z6gmh5J6Q4WJToHu8mBe";
+export const txRollupAddressPtKathman = "txr1R5hkRCJjMugm2Z6gmh5J6Q4WJToHu8mBe";
```
Comment (zainen) [inline integration-tests/known-contracts-PtKathman.ts:6]: this has been removed from master with my pr so it may be a conflict or readded

**Review by zainen — COMMENTED** [review]
Looks good said from the one url and depends on how it rebases on master with the kathamandu removal for integration-tests dir

**Comment by michaelkernaghan** [comment]
> The PR title mentions switching the live code example to using Ghostnet but from looking at the diff I only see changes to the integration tests config

cuz I hadn't done that part yet.

File: integration-tests/known-contracts-PtKathman.ts (hunk 11 above)
Comment (michaelkernaghan) [reply integration-tests/known-contracts-PtKathman.ts:6]: thanks

File: docs/estimate.md (hunk 10 above)
Comment (michaelkernaghan) [reply docs/estimate.md:133]: i'll resolve the conflicts

File: integration-tests/known-contracts-PtKathman.ts [hunk 12]
```diff
@@ -0,0 +1,6 @@
+export const knownContractPtKathman = "KT1SrKKwHMrfMibunFSwuYauMkxnCmmw37fb";
+export const knownBigMapContractPtKathman = "KT1TZWawPbU6mCMa1x6hEZcuZ2RtJxqprskk";
+export const knownTzip12BigMapOffChainContractPtKathman = "KT1WePZzvQxLFmb9QfpLK9rgUVcRPHzjQLhN";
+export const knownSaplingContractPtKathman = "KT1Riu8a1dbWRMmFpMzb9PgdJbhHAAHuvDyJ";
+export const knownOnChainViewContractAddressPtKathman = "KT1My3eKdYKW3H27jZ2oVcNCXGNBDBcTuYiR";
+export const txRollupAddressPtKathman = "txr1R5hkRCJjMugm2Z6gmh5J6Q4WJToHu8mBe";
```
Comment (zainen) [inline integration-tests/known-contracts-PtKathman.ts:6]: this file can be removed since kathmandu is gone

File: docs/estimate.md (hunk 4 above)
Comment (zainen) [inline docs/estimate.md:65]: just curious if this is api.tez.ie for a reason still

**Review by zainen — CHANGES_REQUESTED** [review]

**Review by zainen — APPROVED** [review]
changes look good to me now

**Review by danielelisi — APPROVED** [review]
