### PR TITLE
integration tests: don't hardcode testnet constant values

### LINKED ISSUE #2163: RPC constants integration test "successfully fetches all constants for *net using ${rpc}" hard codes return values
**Description**

The RPC constants integration test "successfully fetches all constants for {kathmandu,monday}net using ${rpc}" hard codes the return values for the RPC call to those returned in the given test network. This makes it hard to run this test against local sandboxed networks where the constants might vary.

**Steps To Reproduce**

1. Start a local sandboxed octez node with RPC endpoint http://localhost:8732 running protocol alpha
2. Run the integration tests, e.g. `TEZOS_RPC_MONDAYNET=http://localhost:8732 RUN_MONDAYNET_WITH_SECRET_KEY=true npm run -w integration-tests test -- --reporters=default --reporters=jest-junit rpc-get-protocol-constants.spec.ts`
3. It will fail.

**Expected behavior**

For example, the test might just check the schema of the constants when the test network is not the real mondaynet / kathmandunet.  

**Additional context**

 This is an issue in TeCI.

### PR DESCRIPTION
**Pull request by arvidj**
Fixes #2163 

This is quite a hacky solution, where the values are only checked if they match an actual RPC endpoint. This means that RPC endpoints have to be updated in two places when they change.

Another possible solution: include a key in the test configurations `configuration.ts::Config` like `testnet: boolean` or `network_type: Testnet | Sandbox`. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

**Comment by roxaneletourneau** [comment]
I am not sure about the suggested changes, because the tests can be run using a different RPC URL. The second option (network_type: Testnet | Sandbox) might be more appropriate.

**Comment by arvidj** [comment]
> I am not sure about the suggested changes, because the tests can be run using a different RPC URL. The second option (network_type: Testnet | Sandbox) might be more appropriate.

Hi, sorry for the slow update. I've implemented what you suggested above, but I had to do some refactoring to simplify the change. What do you think?

**Comment by roxaneletourneau** [comment]
Thank you @arvidj !
Nice cleanup in the config.ts file. 
The changes look good to me. 
I replaced jakartanet with limanet (because we merged our lima branch yesterday to master).

File: integration-tests/originate-known-contracts.ts [hunk 1]
```diff
@@ -16,19 +16,34 @@ CONFIGS().forEach(({ lib, setup, protocol }) => {
...
         console.error(err);
       }
     });
+  };
+
+  (async () => {
+    await setup(true);
+
+    writeOutput("import { KnownContracts } from './known-contracts';")
+    appendOutput("export const knownContracts" + protocolShort + "KnownContracts = {");
```
Comment (roxaneletourneau) [inline integration-tests/originate-known-contracts.ts:40]: I think `KnownContracts` should not be part of the string.

Comment (arvidj) [reply integration-tests/originate-known-contracts.ts]: Pushed a new version, which should fix this. The intention was to concatenate the type annotation, i.e. ` + ": KnownContracts"` but the colon got lost. Should be fixed now.

File: integration-tests/config.ts [hunk 2]
```diff
@@ -75,120 +76,86 @@ const defaultSecretKey: SecretKeyConfig = {
...
+    signerConfig: defaultEphemeralConfig('https://api.tez.ie/keys/kathmandunet')
+  });
+
+const kathmandunetSecretKey: Config =
+  { ...kathmandunetEphemeral, ...{ signerConfig: defaultSecretKey } };
+
+const limanetEphemeral: Config =
+  defaultConfig({
+    networkName: 'LIMANET',
+    protocol: Protocols.PtJakart2,
```
Comment (roxaneletourneau) [inline integration-tests/config.ts:138]: Wrong protocol hash -> should be lima, not jakarta

**Review by roxaneletourneau — CHANGES_REQUESTED** [review]

File: integration-tests/config.ts (hunk 2 above)
Comment (arvidj) [reply integration-tests/config.ts]: Fixed in the latest version.

**Comment by roxaneletourneau** [comment]
There are failures in the flextesa jobs for the "originate-known-contracts" step:
image
I think these outputs are used by the "mondaynet" job, but this could be simplified by using the addresses from "https://github.com/ecadlabs/taquito/blob/master/integration-tests/known-contracts-ProtoALph.ts". Any thoughts about it @danielelisi?

File: integration-tests/originate-known-contracts.ts [hunk 3]
```diff
@@ -7,28 +7,64 @@ import BigNumber from 'bignumber.js';
...
+        .catch((err: any) => {
+          console.error(err);
+        });
+    };
+    let originateKnownContract = async (contractName: string, tezos: TezosToolkit, contractOriginateParams: OriginateParams): Promise<void> => {
+      try {
+        const operation = await tezos.contract.originate(contractOriginateParams);
+        const contract = await operation.contract();
+        console.log(`known ${contractName} address:  ${contract.address}`);
+        console.log(`::set-output ${contractName}::${contract.address}\n`);
```
Comment (danielelisi) [inline integration-tests/originate-known-contracts.ts:43]: This `::set-output` command needs a `name` parameter to fix the issue mentioned in https://github.com/ecadlabs/taquito/pull/2164#issuecomment-1355710953

**Comment by danielelisi** [comment]
> There are failures in the flextesa jobs for the "originate-known-contracts" step: image I think these outputs are used by the "mondaynet" job, but this could be simplified by using the addresses from "https://github.com/ecadlabs/taquito/blob/master/integration-tests/known-contracts-ProtoALph.ts". Any thoughts about it @danielelisi?

Yes either way will work. We need to dynamically originate and pass these contract addresses to the Mondaynet integration test job because the network is reset every week.

**Comment by roxaneletourneau** [comment]
> > There are failures in the flextesa jobs for the "originate-known-contracts" step: image I think these outputs are used by the "mondaynet" job, but this could be simplified by using the addresses from "https://github.com/ecadlabs/taquito/blob/master/integration-tests/known-contracts-ProtoALph.ts". Any thoughts about it @danielelisi?
> 
> Yes either way will work. We need to dynamically originate and pass these contract addresses to the Mondaynet integration test job because the network is reset every week.

Yes, we have two ways of doing the same thing, maybe we should only keep one of them.

**Comment by arvidj** [comment]
> > > There are failures in the flextesa jobs for the "originate-known-contracts" step: image I think these outputs are used by the "mondaynet" job, but this could be simplified by using the addresses from "https://github.com/ecadlabs/taquito/blob/master/integration-tests/known-contracts-ProtoALph.ts". Any thoughts about it @danielelisi?
> > 
> > 
> > Yes either way will work. We need to dynamically originate and pass these contract addresses to the Mondaynet integration test job because the network is reset every week.
> 
> Yes, we have two ways of doing the same thing, maybe we should only keep one of them.

In the latest version, I've restored the format of the `::set-output` command. I now get:
```
> integration-tests@15.0.0 test:originate-known-contracts
> node -r ts-node/register originate-known-contracts.ts

known contract address:  KT1WNPeBPfBjSALHBdhYgUhUAAfPDXvbAYwC
::set-output name=knownContractAddress::KT1WNPeBPfBjSALHBdhYgUhUAAfPDXvbAYwC

known bigMapContract address:  KT19bvsjNpN4KcGB5SfpSvpj8jBcCyfQH5Fm
::set-output name=knownBigMapContractAddress::KT19bvsjNpN4KcGB5SfpSvpj8jBcCyfQH5Fm

known tzip12BigMapOffChainContract address:  KT1CefqoEa95ga6SDWCUfxn2p3rVPmVJ3t1e
::set-output name=knownTzip12BigMapOffChainContractAddress::KT1CefqoEa95ga6SDWCUfxn2p3rVPmVJ3t1e

known saplingContract address:  KT1GzWFKdw7txm1fnjRuMCx913s7V8fLJ1xR
::set-output name=knownSaplingContractAddress::KT1GzWFKdw7txm1fnjRuMCx913s7V8fLJ1xR

known onChainViewContractAddress address:  KT1THQyTne7npn7vyw9WXw4oSbXpoJDY5ZHf
::set-output name=knownOnChainViewContractAddressAddress::KT1THQyTne7npn7vyw9WXw4oSbXpoJDY5ZHf

txRollupAddress:  txr1NFYQM8rkbKX9sqA4MkB6N9ifKp5zzMNZC

################################################################################
```

I can't validate it further though. Guess we'll have to run the flextesa tests?

I also noticed that `::set-output` is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It doesn't seem to hard adopting to the new workflow. I could have `originate-known-contracts.ts` output a JSON file instead, and then read that in `config.ts` respectively `.github/workflows/integration-tests-mondaynet.ts`. 

Preferably in a follow-up PR though :)

**Comment by zainen** [comment]
Hi @arvidj,
Just wanted to check in to see if its ok if i take over the rest of managing the pr and rebasing it. I would have to interact with your forked repo to bring it up to date for the pr 

alternatively could you rebase it and we can merge into another branch that can be finalized

**Comment by arvidj** [comment]
> Hi @arvidj, Just wanted to check in to see if its ok if i take over the rest of managing the pr and rebasing it. I would have to interact with your forked repo to bring it up to date for the pr
> 
> alternatively could you rebase it and we can merge into another branch that can be finalized

Sure, just tell me what I need to do. Sorry for the slow response.

**Comment by zainen** [comment]
Hi @arvidj,
Sorry for the delay! Could you rebase your pr? Then we will merge it into this branch, and then I can finalize it from here and merge it! That way, I won't need to work on your repo 😄

**Comment by arvidj** [comment]
> Hello @arvidj if you have a moment please rebase so @zainen can merge it and finalize :)
> 
> > Hi @arvidj,
> > Sorry for the delay! Could you rebase your pr? Then we will merge it into this branch, and then I can finalize it from here and merge it! That way, I won't need to work on your repo smile

Hi, sorry for the delay. I just pushed a rebased version.

**Comment by arvidj** [comment]
@dsawali I just rebased, could you have a look?
