### PR TITLE
Change Ithacanet integration tests to Kathmandunet

### LINKED ISSUE #1728: convert ithacanet tests in cicd to kathmandunet  tests
The ithacanet will be retiring and the kathmandunet will take over.

update e the integration tests configuration and exceptions

note that ghostnet will be introduced at a later time.

### PR DESCRIPTION
**Pull request by michaelkernaghan**
CLOSE #1728 

updated integration tests and config to work with K protocol.

There are still a number of tests failing that need to be researched for the changes.

### CODE REVIEW

File: packages/taquito-local-forging/src/protocols.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ export enum ProtocolsHash {
   PtHangz2 = 'PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx',
   Psithaca2 = 'Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A',
   PtJakart2 = 'PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY',
+  PtKathman = 'PtKathmanYPEsBau83zRwXK19HAQRzZSj6pCXnvtyLZFjRxdQxt',
```
Comment (roxaneletourneau) [inline packages/taquito-local-forging/src/protocols.ts:13]: It should be `PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg`.

File: packages/taquito-local-forging/src/protocols.ts [hunk 2]
```diff
@@ -25,7 +26,8 @@ const protoLevel: Record<ProtocolsHash, number> = {
   PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx: 11,
   Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A: 12,
   PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY: 13,
-  ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK: 14,
+  PtKathmanYPEsBau83zRwXK19HAQRzZSj6pCXnvtyLZFjRxdQxt: 14,
```
Comment (roxaneletourneau) [inline packages/taquito-local-forging/src/protocols.ts:29]: It should be PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg.

File: packages/taquito-michel-codec/src/michelson-types.ts [hunk 3]
```diff
@@ -386,6 +386,7 @@ export enum Protocol {
   Psithaca2 = 'Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A',
   PtJakarta = 'PtJakartaiDz69SfDDLXJSiuZqTSeSKRDbKVZC8MNzJnvRjvnGw',
   PtJakart2 = 'PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY',
+  PtKathman = 'PtKathmanYPEsBau83zRwXK19HAQRzZSj6pCXnvtyLZFjRxdQxt',
```
Comment (roxaneletourneau) [inline packages/taquito-michel-codec/src/michelson-types.ts:389]: It should be PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg.

File: packages/taquito-michel-codec/src/michelson-types.ts [hunk 4]
```diff
@@ -413,7 +414,8 @@ const protoLevel: Record<ProtocolID, number> = {
   Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A: 12,
   PtJakartaiDz69SfDDLXJSiuZqTSeSKRDbKVZC8MNzJnvRjvnGw: 13,
   PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY: 13,
-  ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK: 14,
+  PtKathmanYPEsBau83zRwXK19HAQRzZSj6pCXnvtyLZFjRxdQxt: 14,
```
Comment (roxaneletourneau) [inline packages/taquito-michel-codec/src/michelson-types.ts:417]: It should be PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg.

File: integration-tests/contract-manager-scenario.spec.ts [hunk 5]
```diff
@@ -50,7 +50,9 @@ CONFIGS().forEach(({ lib, rpc, setup, knownBaker, knownContract }) => {
         await contract.methods.do(MANAGER_LAMBDA.transferImplicit("tz1eY5Aqa1kXDFoiebL28emyXFoneAoVg1zh", 50 * 1000000)).send({ amount: 0 })
         fail('Should throw during transfer with amount higher than balance')
       } catch (ex: any) {
-        expect(ex.message).toMatch('balance_too_low')
+        (protocol === Protocols.PtKathman) ?
```
Comment (roxaneletourneau) [inline integration-tests/contract-manager-scenario.spec.ts:53]: I suppose that mondaynet and later protocols will also return subtraction_underflow?
Should we instead do a check for protocol === Protocols.PtJakart2 and use toContain rather than toMatch?

File: docs/rpc_nodes.md [hunk 6]
```diff
@@ -18,16 +18,16 @@ author: Roxane Letourneau
...
 |------------------|-------------|------------------------------------|-------|
 | ECAD Labs        | Mainnet     | https://mainnet.api.tez.ie         | [Check](https://mainnet.api.tez.ie/chains/main/blocks/head/header)      |
-| ECAD Labs        | Ithacanet   | https://ithacanet.ecadinfra.com    | [Check](https://ithacanet.ecadinfra.com/chains/main/blocks/head/header)      |
+| ECAD Labs        | Kathmandunet   | https://kathmandunet.ecadinfra.com    | [Check](https://kathmandunet.ecadinfra.com/chains/main/blocks/head/header)      |
 | ECAD Labs        | Jakartanet  | https://jakartanet.ecadinfra.com   | [Check](https://jakartanet.ecadinfra.com/chains/main/blocks/head/header)      |
 | SmartPy          | Mainnet     | https://mainnet.smartpy.io         |  [Check](https://mainnet.smartpy.io/chains/main/blocks/head/header)     |
-| SmartPy          | Ithacanet   | https://ithacanet.smartpy.io/      | [Check](https://ithacanet.smartpy.io/chains/main/blocks/head/header)    |
+| SmartPy          | Kathmandunet   | https://kathmandunet.smartpy.io/      | [Check](https://kathmandunet.smartpy.io/chains/main/blocks/head/header)    |
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply docs/rpc_nodes.md:24]: I have changed it to be updated to jakartanet.

We can add K when it is ready.

File: docs/rpc_nodes.md [hunk 7]
```diff
@@ -18,16 +18,16 @@ author: Roxane Letourneau
...
 | Tezos Foundation | Mainnet     | https://rpc.tzbeta.net/            | [Check](https://rpc.tzbeta.net/chains/main/blocks/head/header)      |
 | Tezos Foundation | Jakartanet  | https://rpczero.tzbeta.net/        | [Check](https://rpczero.tzbeta.net/chains/main/blocks/head/header)      |
 | GigaNode         | Mainnet     | https://mainnet-tezos.giganode.io  |  [Check](https://mainnet-tezos.giganode.io/chains/main/blocks/head/header)     |
-| GigaNode         | Ithacanet   | https://testnet-tezos.giganode.io/ | [Check](https://testnet-tezos.giganode.io/chains/main/blocks/head/header)      |
+| GigaNode         | Kathmandunet   | https://testnet-tezos.giganode.io/ | [Check](https://testnet-tezos.giganode.io/chains/main/blocks/head/header)      |
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply docs/rpc_nodes.md:28]: corrected :)

File: docs/rpc_nodes.md [hunk 8]
```diff
@@ -18,16 +18,16 @@ author: Roxane Letourneau
...
 | Marigold         | Mainnet     | https://mainnet.tezos.marigold.dev/    | [Check](https://mainnet.tezos.marigold.dev/chains/main/blocks/head/header)     |
-| Marigold         | Ithacanet   | https://ithacanet.tezos.marigold.dev/  | [Check](https://ithacanet.tezos.marigold.dev/chains/main/blocks/head/header)   |
+| Marigold         | Kathmandunet   | https://kathmandunet.tezos.marigold.dev/  | [Check](https://kathmandunet.tezos.marigold.dev/chains/main/blocks/head/header)   |
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply docs/rpc_nodes.md:30]: removed it until it is ready.

File: integration-tests/contract-big-map.spec.ts [hunk 9]
```diff
@@ -204,6 +204,7 @@ CONFIGS().forEach(({ lib, rpc, setup, knownBigMapContract }) => {
       done();
     });
 
+    // ISSUE #1751
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-big-map.spec.ts:207]: I removed the comment and closed issue 1751.

File: integration-tests/contract-estimation-tests.spec.ts [hunk 10]
```diff
@@ -309,32 +309,32 @@ CONFIGS().forEach(({ lib, setup, knownBaker, createAddress, protocol, rpc }) =>
...
+      expect(estimate.totalCost).toEqual(360);
+      expect(estimate.usingBaseFeeMutez).toEqual(360);
+      expect(estimate.consumedMilligas).toEqual(1000040);
       done();
     });
 
-    it('Estimate transfer to regular address with a fixed fee', async (done) => {
+    jakartanet('Estimate transfer to regular address with a fixed fee', async (done) => {
       // fee, gasLimit and storage limit are not taken into account
+      //const params = { fee: 2000, to: await Tezos.signer.publicKeyHash(), mutez: true, amount: amt - (1382 + DEFAULT_FEE.REVEAL) }
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-estimation-tests.spec.ts:327]: removed

File: integration-tests/contract-originate-contract-with-sapling.spec.ts [hunk 11]
```diff
@@ -17,7 +17,7 @@ import {
 CONFIGS().forEach(({ lib, rpc, protocol, setup }) => {
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-originate-contract-with-sapling.spec.ts:17]: all are common now.

File: integration-tests/contract-originate-contract-with-single-sapling-state.spec.ts [hunk 12]
```diff
@@ -1,39 +1,25 @@
...
-  const jakartanetAndMondaynet = protocol === Protocols.ProtoALpha || protocol === Protocols.PtJakart2 ? test: test.skip;
 
   describe(`Test origination of contracts with sapling using: ${rpc}`, () => {
     beforeEach(async (done) => {
       await setup();
       done();
     });
 
-    ithacanet('Originates a contract with a single sapling state in its storage for Ithaca', async (done) => {
+    test('Originates a contract with a single sapling state in its storage for kathmandu', async (done) => {
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-originate-contract-with-single-sapling-state.spec.ts:13]: fixed

File: integration-tests/contract-security-mutez-underflow.spec.ts [hunk 13]
```diff
@@ -10,14 +10,15 @@ import { CONFIGS } from './config';
...
+  const kathmandunet = protocol === Protocols.PtKathman ? test : test.skip;
 
   describe(`Test contracts using: ${rpc}`, () => {
     beforeEach(async (done) => {
       await setup();
       done();
     });
 
-    mondaynet('Verify mutez underflow example', async (done) => {
+    kathmandunet('Verify mutez underflow example', async (done) => {
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-security-mutez-underflow.spec.ts:21]: fixed

File: integration-tests/contract-security-non-existent-KT-address.spec.ts [hunk 14]
```diff
@@ -6,7 +6,7 @@ import { Protocols, TezosToolkit } from '@taquito/taquito';
 
 // KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn is the tzBTC contract on mainnet
 
-const Tezos = new TezosToolkit(new RpcClient(' https://ithacanet.ecadinfra.com'));
+const Tezos = new TezosToolkit(new RpcClient(' https://kathmandunet.ecadinfra.com'));
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-security-non-existent-KT-address.spec.ts:9]: fixed

File: integration-tests/rpc-get-protocol-constants.spec.ts [hunk 15]
```diff
@@ -5,7 +5,8 @@ import { ConstantsResponseCommon, ConstantsResponseProto009, ConstantsResponsePr
 
 CONFIGS().forEach(({ lib, protocol, rpc }) => {
     const Tezos = lib;
-
+   
+    const kathmandunet = (protocol === Protocols.PtKathman) ? test : test.skip;
     const jakartanet = (protocol === Protocols.PtJakart2) ? test : test.skip;
     const ithacanet = (protocol === Protocols.Psithaca2) ? test : test.skip;
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/rpc-get-protocol-constants.spec.ts:11]: removed

File: packages/taquito-local-forging/src/protocols.ts (hunk 1 above)
Comment (michaelkernaghan) [reply packages/taquito-local-forging/src/protocols.ts:13]: fixed

File: packages/taquito-local-forging/src/protocols.ts (hunk 2 above)
Comment (michaelkernaghan) [reply packages/taquito-local-forging/src/protocols.ts:29]: fixed

File: packages/taquito-michel-codec/src/michelson-types.ts (hunk 3 above)
Comment (michaelkernaghan) [reply packages/taquito-michel-codec/src/michelson-types.ts:389]: fixed

File: packages/taquito-michel-codec/src/michelson-types.ts (hunk 4 above)
Comment (michaelkernaghan) [reply packages/taquito-michel-codec/src/michelson-types.ts:417]: fixed

**Comment by roxaneletourneau** [comment]
We need a job for kathmandu as well in the following file: https://github.com/ecadlabs/taquito/blob/master/.github/workflows/main.yml#L38
to run the tests in the pipeline against kathmandunet

File: integration-tests/contract-manager-scenario.spec.ts (hunk 5 above)
Comment (michaelkernaghan) [reply integration-tests/contract-manager-scenario.spec.ts:53]: I have changed it, so it checks for Jakarta for an exception. Otherwise, it will assume the new returned value.
I change to "ToContain" as well.

File: integration-tests/contract-estimation-tests.spec.ts [hunk 16]
```diff
@@ -365,5 +365,39 @@ CONFIGS().forEach(({ lib, setup, knownBaker, createAddress, protocol, rpc }) =>
...
     })
+
+    kathmandunet('Estimate transfer to regular address with a fixed fee', async (done) => {
+      // fee, gasLimit and storage limit are not taken into account
+      //const params = { fee: 2000, to: await Tezos.signer.publicKeyHash(), mutez: true, amount: amt - (1382 + DEFAULT_FEE.REVEAL) }
+      const params = { fee: 2000, to: await Tezos.signer.publicKeyHash(), mutez: true, amount: amt - (1382 + DEFAULT_FEE.REVEAL) }
+
+      await expect(LowAmountTez.estimate.transfer(params)).rejects
+      .toMatchObject({
+            id: 'proto.014-PtKathma.implicit.empty_implicit_contract',
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/contract-estimation-tests.spec.ts:375]: we figured this out in a later discussion.

File: integration-tests/wallet-manager-scenario.spec.ts [hunk 17]
```diff
@@ -50,7 +50,9 @@ CONFIGS().forEach(({ lib, rpc, setup, knownBaker, knownContract }) => {
         await contract.methods.do(MANAGER_LAMBDA.transferImplicit("tz1eY5Aqa1kXDFoiebL28emyXFoneAoVg1zh", 50 * 1000000)).send({ amount: 0 })
         fail('Should throw during transfer with amount higher than balance')
       } catch (ex: any) {
-        expect(ex.message).toMatch('balance_too_low')
+        (protocol === Protocols.PtKathman) ?
```
[the remark this answers is not in the document]
Comment (michaelkernaghan) [reply integration-tests/wallet-manager-scenario.spec.ts:56]: I have corrected this test. the conditional has been changed to check for Jakarta or other and the match has been changed to ToContain

File: integration-tests/rpc-nodes.spec.ts [hunk 18]
```diff
@@ -399,17 +388,17 @@ CONFIGS().forEach(
...
           expect(inbox).toBeDefined();
           done();
         });
 
-        jakartanetIt('getTxRollupState', async (done) => {
-          const state = await rpcClient.getTxRollupState('txr1YTdi9BktRmybwhgkhRK7WPrutEWVGJT7w');
-          expect(state).toBeDefined();
-          done();
-        });
+        // it('getTxRollupState', async (done) => {
```
Comment (roxaneletourneau) [inline integration-tests/rpc-nodes.spec.ts:397]: Why is this test commented?

Comment (michaelkernaghan) [reply integration-tests/rpc-nodes.spec.ts:397]: waiting for the endpoint to be re-activated. But I understand the test needs a new rollup address, so  I will fix it.

Comment (michaelkernaghan) [reply integration-tests/rpc-nodes.spec.ts]: repaired the test by splitting the j and K tests to each use its an appropriate rollup address

**Comment by michaelkernaghan** [comment]
squash

**Comment by michaelkernaghan** [comment]
closed by mistake, reponed, then merged properly,
