### PR TITLE
Issue-960 Changes for ExtractSchema for token type list

### LINKED ISSUE #960: Schema.ExtractSchema() returns "list"
**Description**

The method [`ExtractSchema()` of `Schema`](https://tezostaquito.io/docs/michelson_encoder/#the-extractschema-method) returns string `"list"` for a complex Michelson starting with a `{ prim: 'list' }`. Or am I wrong and this is an expected exception?

**Steps To Reproduce**
1. Run following code.
    ```typescript
    const storageType = {
        prim: 'list',
        args: [
            {
                prim: 'pair',
                args: [
                    { prim: 'address', annots: ['%from'] },
                    { prim: 'address', annots: ['%to'] },
                ],
            },
        ],
    };
    const storageSchema = new Schema(storageType);
    const extractSchema = storageSchema.ExtractSchema();
    println(JSON.stringify(extractSchema, null, 2));
    ```
2. It prints (returns) string `"list"`.

**Expected behavior**
Expected to return complex object like:
```typescript
[
    {
        "from": "address",
        "to": "address"
    }
]
```

### PR DESCRIPTION
**Pull request by kjaiswal**
Resolves #960

### CODE REVIEW

File: packages/taquito-michelson-encoder/src/tokens/list.ts [hunk 1]
```diff
@@ -67,6 +67,10 @@ export class ListToken extends Token {
   }
 
   public ExtractSchema() {
-    return ListToken.prim;
+    const valueSchema = this.createToken(this.val.args[0], this.idx);
+    return {
```
Comment (roxaneletourneau) [inline packages/taquito-michelson-encoder/src/tokens/list.ts:71]: The main purpose of MichelsonEncoder is to abstract Michelson language and "prim" is really something proper to the Michelson language. Thus, I don't think we should return a "prim" in the schema.
An alternative could be:
```
return {
ListToken.prim: valueSchema.ExtractSchema()
}
```

Comment (kjaiswal) [reply packages/taquito-michelson-encoder/src/tokens/list.ts:71]: This has been fixed.

**Review by roxaneletourneau — APPROVED** [review]
