### PR TITLE
1993 fix duplicate errors

### LINKED ISSUE #1993: Consolidate duplicated Errors across packages
_Follow up of https://github.com/ecadlabs/taquito/issues/160_ as described in https://hackmd.io/@tca0T8LZT3au8LG6hSX20g/r1zTRTlfj_

Task 2: Consolidate duplicated Errors across packages (InvalidViewParameterError, InvalidAddressError, InvalidBlockHashError, InvalidHexStringError, InvalidMessageError, ...)

### PR DESCRIPTION
**Pull request by zainen**
moves duplicates to taquito/core

two changed class names for clairty since joining the classes would have obscured the reason error and the name of the error

new classes 
InvalidContractViewParameterError (previously InvalidViewParameterError) -> may want to change the other as its in tzip16 and would be less disruptive than changing whats in `@taquito`
InvalidHashLengthError (previously InvalidMessageError)

moved other duplicates with possible minor change of adding either a message or param to the constructor based on needs

will merge into branch [1992-create-high-level-categories-of-errors](https://github.com/ecadlabs/taquito/tree/1992-create-high-level-categories-of-errors) if not merged first 

closes #1993

### CODE REVIEW

**Comment by zainen** [comment]
missed updating a test. will update

File: packages/taquito-contracts-library/src/errors.ts [hunk 1]
```diff
@@ -1,12 +1,4 @@
-/**
- *  @category Error
- *  @description Error that indicates an invalid address being used or passed
- */
-export class InvalidAddressError extends Error {
-  constructor(message: string) {
-    super(message);
-  }
-}
+export * from '@taquito/core';
```
Comment (hui-an-yang) [inline packages/taquito-contracts-library/src/errors.ts:1]: this file path seem renamed to `packages/taquito-contracts-library/src/taquito-core.ts` ?

File: packages/taquito-ledger-signer/src/taquito-ledger-signer.ts [hunk 2]
```diff
@@ -43,19 +44,6 @@ export class InvalidDerivationTypeError extends Error {
   }
 }
```
Comment (dsawali) [inline packages/taquito-ledger-signer/src/taquito-ledger-signer.ts:45]: shouldn't `InvalidDerivationTypeError` be moved to error.ts as well?

File: packages/taquito-local-forging/src/taquito-local-forging.ts [hunk 3]
```diff
@@ -3,13 +3,14 @@
...
 
+import { InvalidBlockHashError } from './error';
 import { ForgeParams, Forger } from './interface';
 import { CODEC } from './constants';
 import { decoders } from './decoder';
 import { encoders } from './encoder';
 import { Uint8ArrayConsumer } from './uint8array-consumer';
 import { validateBlock, ValidationResult, InvalidOperationKindError } from '@taquito/utils';
-import { InvalidBlockHashError, InvalidOperationSchemaError } from './error';
+import { InvalidOperationSchemaError } from './error';
```
Comment (dsawali) [inline packages/taquito-local-forging/src/taquito-local-forging.ts:13]: this and `InvalidBlockHashError` in line 6 seems like they're from the same file. Are there any reason they are on different import statements?

File: packages/taquito-local-forging/src/michelson/codec.ts [hunk 4]
```diff
@@ -135,8 +135,8 @@ export const intEncoder: Encoder<IntValue> = ({ int }) => {
     binary.length <= 6
       ? 6
       : (binary.length - 6) % 7
-      ? binary.length + 7 - ((binary.length - 6) % 7)
-      : binary.length;
+        ? binary.length + 7 - ((binary.length - 6) % 7)
```
Comment (dsawali) [inline packages/taquito-local-forging/src/michelson/codec.ts:138]: is this from the lint, or is the whitespace unintended?

File: packages/taquito-local-forging/src/uint8array-consumer.ts [hunk 5]
```diff
@@ -8,11 +9,11 @@ export class Uint8ArrayConsumer {
       );
       return new Uint8ArrayConsumer(arr);
     } else {
-      throw new InvalidHexStringError(lowHex);
+      throw new InvalidHexStringError(`The hex string '${lowHex}' is invalid`);
     }
   }
 
-  constructor(private readonly arr: Uint8Array, private offset: number = 0) {}
+  constructor(private readonly arr: Uint8Array, private offset: number = 0) { }
```
Comment (dsawali) [inline packages/taquito-local-forging/src/uint8array-consumer.ts:16]: I think the previous was correct (no whitespace in between curly brackets)

File: packages/taquito-signer/src/derivation-tools/ed25519.ts [hunk 6]
```diff
@@ -4,7 +4,8 @@ import { SHA512 } from '@stablelib/sha512';
 import { generateKeyPairFromSeed } from '@stablelib/ed25519';
 import { ExtendedPrivateKey, Hard } from './index';
 import { parseHex } from './utils';
-import { InvalidDerivationPathError, InvalidSeedLengthError } from '../errors';
+import { InvalidSeedLengthError } from '../errors';
+import { InvalidDerivationPathError } from '../errors';
```
Comment (dsawali) [inline packages/taquito-signer/src/derivation-tools/ed25519.ts:8]: not sure why they're on different lines, they should be from the same file it seems

File: packages/taquito-signer/src/derivation-tools/utils.ts [hunk 7]
```diff
@@ -1,4 +1,5 @@
-import { InvalidHexStringError } from "@taquito/utils";
+import { InvalidHexStringError } from '../errors';
```
Comment (dsawali) [inline packages/taquito-signer/src/derivation-tools/utils.ts:1]: I see this happening in a few files where a common error is being imported from `@taquito/core` and is re-exported into the file that needs it. I think for those cases we should instead import directly from `@taquito/core`.

The only case where we'd need to import and re-export is when the error used to live in the package, but is then moved into `@taquito/core`. We should be leveraging direct imports from `@taquito/core` wherever possible

File: packages/taquito/src/batch/rpc-batch-provider.ts [hunk 8]
```diff
@@ -326,7 +326,7 @@ export class OperationBatch extends OperationEmitter {
 }
 
 export class RPCBatchProvider {
-  constructor(private context: Context, private estimator: EstimationProvider) {}
+  constructor(private context: Context, private estimator: EstimationProvider) { }
```
Comment (dsawali) [inline packages/taquito/src/batch/rpc-batch-provider.ts:329]: same comment here about the whitespace

File: packages/taquito/src/wallet/wallet.ts [hunk 9]
```diff
@@ -37,7 +37,7 @@ export type WalletParamsWithKind =
 export class WalletOperationBatch {
   private operations: WalletParamsWithKind[] = [];
 
-  constructor(private walletProvider: WalletProvider, private context: Context) {}
+  constructor(private walletProvider: WalletProvider, private context: Context) { }
```
Comment (dsawali) [inline packages/taquito/src/wallet/wallet.ts:40]: same comment here on the whitespace

File: packages/taquito/src/wallet/wallet.ts [hunk 10]
```diff
@@ -156,7 +156,7 @@ export class WalletOperationBatch {
 }
 
 export class Wallet {
-  constructor(private context: Context) {}
+  constructor(private context: Context) { }
```
Comment (dsawali) [inline packages/taquito/src/wallet/wallet.ts:159]: whitespace

File: packages/taquito/test/estimate/rpc-estimate-provider.spec.ts [hunk 11]
```diff
@@ -26,7 +26,9 @@ import {
 } from '../contract/helper';
 import { OpKind } from '@taquito/rpc';
 import { TransferTicketParams } from '../../src/operations/types';
-import { InvalidAddressError, InvalidContractAddressError } from '@taquito/utils';
+import { InvalidContractAddressError } from '@taquito/utils';
```
Comment (dsawali) [inline packages/taquito/test/estimate/rpc-estimate-provider.spec.ts:29]: I think this can be moved/extended from `@taquito/core` as it's basically a parameter error or a `InvalidXError` but perhaps that's for the other ticket

**Review by dsawali — CHANGES_REQUESTED** [review]

File: packages/taquito-contracts-library/test/taquito-contracts-library.spec.ts [hunk 12]
```diff
@@ -106,7 +107,7 @@ describe('ContractsLibrary tests', () => {
       })
     ).toThrow(
       expect.objectContaining({
-        message: expect.stringContaining('Address is invalid: KTinvalid'),
+        message: expect.stringContaining("The address 'KTinvalid' is invalid"),
```
[the remark this answers is not in the document]
Comment (zainen) [reply packages/taquito-contracts-library/test/taquito-contracts-library.spec.ts:110]: 👍

File: packages/taquito-ledger-signer/src/error.ts [hunk 13]
```diff
@@ -1,3 +1,5 @@
+export { InvalidDerivationPathError } from '@taquito/core';
```
[the remark this answers is not in the document]
Comment (zainen) [reply packages/taquito-ledger-signer/src/error.ts:1]: i have done these to keep them exportable from the same file to make it exportable from the index of this package or the file that contains it

[the remark this answers is not in the document]
Comment (zainen) [reply packages/taquito-ledger-signer/src/error.ts:1]: to stop breaking changes of moving it to taquito core

File: packages/taquito-contracts-library/test/taquito-contracts-library.spec.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (zainen) [reply packages/taquito-contracts-library/test/taquito-contracts-library.spec.ts:110]: split the InvalidAddress with InvalidContractAddress but didnt change this one. changed now

File: packages/taquito-ledger-signer/src/taquito-ledger-signer.ts (hunk 2 above)
Comment (zainen) [reply packages/taquito-ledger-signer/src/taquito-ledger-signer.ts:45]: was already moved an imported just missed clearing the declaration

Comment (zainen) [reply packages/taquito-ledger-signer/src/taquito-ledger-signer.ts:45]: nvm see what i missed

File: packages/taquito-local-forging/src/taquito-local-forging.ts (hunk 3 above)
Comment (zainen) [reply packages/taquito-local-forging/src/taquito-local-forging.ts:13]: thanks for the catch put imported from taquito/core then switched it to error

File: packages/taquito-local-forging/src/michelson/codec.ts (hunk 4 above)
Comment (zainen) [reply packages/taquito-local-forging/src/michelson/codec.ts:138]: this is from formatting for the aligning of different ternary operators
should it be reverted? i think it looks a little more clear for the different ternary cases

File: packages/taquito-local-forging/src/uint8array-consumer.ts (hunk 5 above)
Comment (zainen) [reply packages/taquito-local-forging/src/uint8array-consumer.ts:16]: yea i need to change my formatter since it is default for that 

only spaces we want between curly braces is with variables inbetween right? for the braces that are opened and closed on the same line

File: packages/taquito-signer/src/derivation-tools/utils.ts (hunk 7 above)
Comment (zainen) [reply packages/taquito-signer/src/derivation-tools/utils.ts:1]: good point i'll make sure to change them import directly from taquito/core
just wanted to be consistent and picked the import path that was longer 😓

File: packages/taquito/test/estimate/rpc-estimate-provider.spec.ts (hunk 11 above)
Comment (zainen) [reply packages/taquito/test/estimate/rpc-estimate-provider.spec.ts:29]: i have moved it to taquito core!

Comment (zainen) [reply packages/taquito/test/estimate/rpc-estimate-provider.spec.ts:29]: will push soon

File: packages/taquito-local-forging/src/taquito-local-forging.ts [hunk 14]
```diff
@@ -47,7 +47,7 @@ export function getCodec(codec: CODEC, _proto: ProtocolsHash) {
 }
 
 export class LocalForger implements Forger {
-  constructor(public readonly protocolHash = PROTOCOL_CURRENT) {}
+  constructor(public readonly protocolHash = PROTOCOL_CURRENT) { }
```
Comment (dsawali) [inline packages/taquito-local-forging/src/taquito-local-forging.ts:50]: should remove the whitespace between curly brackets

File: packages/taquito-ledger-signer/src/error.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (dsawali) [reply packages/taquito-ledger-signer/src/error.ts:1]: wouldn't it make more sense to keep InvalidDerivationPathError in this package instead of moving it up to`core`? Or was there a reason why it might need to be put up there?

[the remark this answers is not in the document]
Comment (dsawali) [reply packages/taquito-ledger-signer/src/error.ts:1]: if it's not like a shared across packages thing, like say, `InvalidAddressError` or something like that. Might want to keep it contained in the package it's referenced at instead. But I might be missing context

File: packages/taquito-core/src/error/common.ts [hunk 15]
```diff
@@ -0,0 +1,45 @@
+/**
+ *  @category Error
+ *  @description Error that indicates an invalid address being passed or used (both contract and implicit)
```
Comment (hui-an-yang) [inline packages/taquito-core/src/error/common.ts:3]: Thinking with InvalidContractAddressError being distinguished that InvalidAddressError will just be implicit?

File: packages/taquito-core/src/error/common.ts [hunk 16]
```diff
@@ -0,0 +1,45 @@
...
+ */
+export class InvalidAddressError extends Error {
```
Comment (hui-an-yang) [inline packages/taquito-core/src/error/common.ts:5]: Unsure I understand the context correctly, I thought we plan to extend common errors by higher level errors created by task1?

File: packages/taquito-local-forging/package.json [hunk 17]
```diff
@@ -73,6 +73,7 @@
   },
   "devDependencies": {
     "@taquito/rpc": "^15.0.1",
+    "@taquito/core": "^15.0.0",
```
Comment (hui-an-yang) [inline packages/taquito-local-forging/package.json:76]: Saw your comments in a channel the other day agree that we should update taquito/core to ^15.0.1 to align with other packages.

File: packages/taquito/test/estimate/rpc-estimate-provider.spec.ts [hunk 18]
```diff
@@ -26,7 +26,9 @@ import {
 } from '../contract/helper';
 import { OpKind } from '@taquito/rpc';
 import { TransferTicketParams } from '../../src/operations/types';
-import { InvalidAddressError, InvalidContractAddressError } from '@taquito/utils';
+import { InvalidContractAddressError } from '@taquito/core';
```
Comment (hui-an-yang) [inline packages/taquito/test/estimate/rpc-estimate-provider.spec.ts:29]: if line 29 and 30 are both importing from @taquito/core, will we consider to make it one line?

File: packages/taquito-utils/src/taquito-utils.ts [hunk 19]
```diff
@@ -131,7 +132,7 @@ export function b58decodeL2Address(payload: string) {
  */
 export function encodePubKey(value: string) {
   if (value.substring(0, 2) === '00') {
-    const pref: { [key: string]: Uint8Array } = {
+    const pref: { [key: string]: Uint8Array; } = {
```
Comment (hui-an-yang) [inline packages/taquito-utils/src/taquito-utils.ts:135]: Am curious are these semi-colons in curly brackets from linter? Would like to know why it only pops up now?

**Review by hui-an-yang — COMMENTED** [review]
Would like to know what is the rule of thumb to put error classes in common or not? Feeling like many classes in `packages/taquito-utils/src/errors.ts` are used in other packages can be moved to `packages/taquito-core/src/error/common.ts` to remove circular dependency too.  I understand to avoid breaking changes the best we can, so would like to know under what conditions we put it in `common.ts` file?

File: packages/taquito-core/src/error/common.ts (hunk 16 above)
Comment (zainen) [reply packages/taquito-core/src/error/common.ts:5]: this is just moving the current error to common. we can change what it extends after this ticket

File: packages/taquito-utils/src/taquito-utils.ts (hunk 19 above)
Comment (zainen) [reply packages/taquito-utils/src/taquito-utils.ts:135]: from my formatter 
types want to be ended with `;`  even for values of keys in objects

File: packages/taquito-ledger-signer/src/error.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (zainen) [reply packages/taquito-ledger-signer/src/error.ts:1]: its used in both taquito signer and taquito ledger signer

File: packages/taquito-contracts-library/src/errors.ts (hunk 1 above)
Comment (hui-an-yang) [inline packages/taquito-contracts-library/src/errors.ts:1]: Would like to understand is there a reason behind exporting the entire @taquito/core package here instead of specific classes used in this package like the rest of the code change?

Comment (zainen) [reply packages/taquito-contracts-library/src/errors.ts:1]: this is to just stop breaking changes from happening for moving errors from thats that they would otherwise have been coming from

Comment (zainen) [reply packages/taquito-contracts-library/src/errors.ts:1]: in case anyone is importing from the error file directly

File: packages/taquito-core/src/error/common.ts (hunk 16 above)
Comment (hui-an-yang) [reply packages/taquito-core/src/error/common.ts:5]: I see, so taquito/core will also be one of the package that we'll work on ticket 1994. Since common.ts will be used across packages do we want to prioritize as first 5 that we'll tackle?

File: packages/taquito-local-forging/src/error.ts [hunk 20]
```diff
@@ -1,15 +1,6 @@
...
- *  @category Error
- *  @description Error that indicates an invalid block hash being passed or used
- */
-export class InvalidBlockHashError extends Error {
-  public name = 'InvalidBlockHashError';
-  constructor(public message: string) {
-    super(message);
-  }
-}
+export { InvalidAddressError, InvalidHexStringError } from '@taquito/core';
```
Comment (hui-an-yang) [inline packages/taquito-local-forging/src/error.ts:3]: Didn't see InvalidAddressError export here previously, would like to understand why we'd like to export here now?

File: packages/taquito-utils/src/errors.ts [hunk 21]
```diff
@@ -1,3 +1,5 @@
+export { InvalidHexStringError, InvalidContractAddressError } from '@taquito/core';
```
Comment (hui-an-yang) [inline packages/taquito-utils/src/errors.ts:1]: Do we also want to export InvalidAddressError, InvalidBlockHashError here to avoid breaking changes?

File: packages/taquito-local-forging/src/error.ts (hunk 20 above)
Comment (zainen) [reply packages/taquito-local-forging/src/error.ts]: thanks for the catch

File: packages/taquito-core/src/error/common.ts (hunk 16 above)
Comment (zainen) [reply packages/taquito-core/src/error/common.ts:5]: yes because any modifications of locations or additions of higher level functions will add to taquito/core

**Review by dsawali — APPROVED** [review]

**Comment by dsawali** [comment]
> Would like to know what is the rule of thumb to put error classes in common or not? Feeling like many classes in `packages/taquito-utils/src/errors.ts` are used in other packages can be moved to `packages/taquito-core/src/error/common.ts` to remove circular dependency too. I understand to avoid breaking changes the best we can, so would like to know under what conditions we put it in `common.ts` file?

I agree, we should probably centralize them in core now

**Review by hui-an-yang — APPROVED** [review]
except for `export * from '@taquito/core';` in `packages/taquito-contracts-library/src/errors.ts` to be error class specific the rest lgtm :)
