### PR TITLE
1996 rpc 2

### LINKED ISSUE #1996: Provide appropriate error based on Taquito context when the RPC returns an exception
_Follow up of https://github.com/ecadlabs/taquito/issues/160_ as described in https://hackmd.io/@tca0T8LZT3au8LG6hSX20g/r1zTRTlfj_

Task 5: Pay specific attention to the error returned by the RPC. Sometimes, the error is vague and not informative enough according to the context. We should provide a custom error with additional information in those cases. 

TODO: use Taquito in different ways to generate failure from the RPC, inspect the error coming from the RPC, identify error messages that would benefit from clarification, and make the appropriate changes. Here are two examples that need to be addressed: 
- When trying to fetch a big map value using a key of the wrong type (for example, using X where a nat was expected), an error from the node bubble up and is hard to diagnose: 
```
    Uncaught (in promise) HttpResponse: Http error response: (400) Failed to parse the request body: No case matched:
      Unhandled error (Invalid_argument "Z.of_substring_base: invalid digit")
      Missing object field string
      Missing object field bytes
      Unexpected object instead of array
      Missing object field prim
        at HttpBackend.<anonymous> (http://localhost:3030/node_modules/.vite/deps/chunk-V4G7R2DB.js?v=4243d8f3:1552:17)
        at Generator.throw (<anonymous>)
        at rejected (http://localhost:3030/node_modules/.vite/deps/chunk-V4G7R2DB.js?v=4243d8f3:1390:32)
```
    
- An error comes from the RPC when estimating an operation using an account with a balance too low (https://github.com/ecadlabs/taquito/issues/363). TODO: validate if the behavior is still the same; the issue was opened in 2020.
```
    HttpResponseError {
      message: 'Http error response: (400) Failed to parse the request body: No case matched:\n' +
        '  At /kind, unexpected string instead of endorsement\n' +
        '  At /kind, unexpected string instead of seed_nonce_revelation\n' +
        '  At /kind, unexpected string instead of double_endorsement_evidence\n' +
        '  At /kind, unexpected string instead of double_baking_evidence\n' +
        '  At /kind, unexpected string instead of activate_account\n' +
        '  At /kind, unexpected string instead of proposals\n' +
        '  At /kind, unexpected string instead of ballot\n' +
        '  At /kind, unexpected string instead of reveal\n' +
        '  At /destination:\n' +
        '    Unhandled error (Failure "Invalid contract notation.")\n' +
        '  At /kind, unexpected string instead of origination\n' +
        '  At /kind, unexpected string instead of delegation',
      status: 400,
      statusText: 'Bad Request',
      body: 'Failed to parse the request body: No case matched:\n' +
        '  At /kind, unexpected string instead of endorsement\n' +
        '  At /kind, unexpected string instead of seed_nonce_revelation\n' +
        '  At /kind, unexpected string instead of double_endorsement_evidence\n' +
        '  At /kind, unexpected string instead of double_baking_evidence\n' +
        '  At /kind, unexpected string instead of activate_account\n' +
        '  At /kind, unexpected string instead of proposals\n' +
        '  At /kind, unexpected string instead of ballot\n' +
        '  At /kind, unexpected string instead of reveal\n' +
        '  At /destination:\n' +
        '    Unhandled error (Failure "Invalid contract notation.")\n' +
        '  At /kind, unexpected string instead of origination\n' +
        '  At /kind, unexpected string instead of delegation',
      name: 'HttpResponse'
    }
```

### PR DESCRIPTION
**Pull request by dsawali**
closes #1996 

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have run the linter against the changes
- [ ] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [ ] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [ ] You have added a concise description on your changes
## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

File: packages/taquito/src/contract/rpc-contract-provider.ts [hunk 1]
```diff
@@ -393,9 +399,9 @@ export class RpcContractProvider extends Provider implements ContractProvider, S
     if (destinationValidation !== ValidationResult.VALID) {
       throw new InvalidAddressError(params.destination, invalidDetail(destinationValidation));
     }
-    const srouceValidation = validateAddress(params.source ?? '');
-    if (params.source && srouceValidation !== ValidationResult.VALID) {
-      throw new InvalidAddressError(params.source, invalidDetail(srouceValidation));
+    const sourceValidation = validateAddress(params.source ?? '');
```
Comment (hui-an-yang) [inline packages/taquito/src/contract/rpc-contract-provider.ts:402]: thanks, good catch!

**Review by AlirezaHaghshenas — APPROVED** [review]

**Review by hui-an-yang — APPROVED** [review]
lgtm🙌
