### PR TITLE
fix(confirmationPollingTimeoutSecond): fix for contract/wallet API

### LINKED ISSUE #2006: confirmationPollingTimeoutSecond not working
**Description**
There is an issue with the `confirmationPollingTimeoutSecond` on the TezosToolkit. During the operation confirmation (both on the contract and wallet  API), the timer for the timeout seems to restart to 0 on every emission of a new block.

**Steps To Reproduce**

Execute the following code:
```
Tezos.setProvider({config: {confirmationPollingTimeoutSecond:15}})
const op = await Tezos.contract.originate({
        balance: "1",
        code: `parameter string;
        storage string;
        code {CAR;
              PUSH string "Hello ";
              CONCAT;
              NIL operation; PAIR};
        `,
        init: `"test"`,
        gasLimit:800000
})
await op.confirmation()
```
**Expected behavior**
We set a high `gasLimit`, so the operation will not be included in a block. We set a timeout of 15 seconds and expect that an error `'Confirmation polling timed out'` will be thrown after 15 seconds. The error is not thrown.

**Desktop (please complete the following information):**
 - Version 14.0.0

### PR DESCRIPTION
**Pull request by roxaneletourneau**
The timeout was not taken into consideration on both the contract and wallet API when confirming the operations. In cases where an operation was not found, our integration tests would never end instead of throwing a timeout error.

fix #2006

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have added unit tests
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

File: packages/taquito/src/wallet/operation.ts [hunk 1]
```diff
@@ -64,7 +66,8 @@ export class WalletOperation {
       return typeof x !== 'undefined';
     }),
     first(),
-    shareReplay({ bufferSize: 1, refCount: true })
+    publishReplay(1),
```
Comment (dsawali) [inline packages/taquito/src/wallet/operation.ts:69]: I think publishReplay will be removed in version 8 of RxJS. https://rxjs.dev/api/operators/publishReplay#publishreplay

File: integration-tests/contract-confirmation-timeout.spec.ts [hunk 2]
```diff
@@ -0,0 +1,40 @@
+import BigNumber from "bignumber.js";
+import { CONFIGS } from "./config";
+
+const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
```
Comment (dsawali) [inline integration-tests/contract-confirmation-timeout.spec.ts:4]: since we used this more than a couple times now, perhaps we should create a utils.ts file in `integration-tests`?

File: packages/taquito/src/wallet/operation.ts (hunk 1 above)
Comment (dsawali) [reply packages/taquito/src/wallet/operation.ts:69]: It's prob not that big of a deal, but just something to keep in mind if we some day want to upgrade to RxJS 8

File: integration-tests/contract-confirmation-timeout.spec.ts (hunk 2 above)
Comment (roxaneletourneau) [reply integration-tests/contract-confirmation-timeout.spec.ts:4]: Make sense, I will create the utils file, thanks.

**Review by dsawali — APPROVED** [review]

File: integration-tests/contract-confirmation-timeout.spec.ts (hunk 2 above)
Comment (roxaneletourneau) [reply integration-tests/contract-confirmation-timeout.spec.ts]: Moved to the config.ts file instead
